plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.gaobieshi'
version = '0.1.0'

base {
    archivesName = 'gaobieshi-security'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
            'Specification-Title': 'gaobieshi-security',
            'Specification-Vendor': 'gaobieshi',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'gaobieshi'
        ])
    }
}

